### ISSUE TITLE
Make use case diagram prettier

### ISSUE THREAD

**Issue by NgyAnthony** [NgyAnthony/supinfo-2ccpp#1]
Either make a diagram for each category/related use cases or make it more spaced/even.

**Comment by NgyAnthony** [comment]
I think we should create multiple diagrams instead of having one big diagram. There's way too many use cases and it becomes unclear.

**Comment by 305781** [comment]
yes we shall make mutliple diagrams depending on classes and objects the use case is about maybe, like use cases for reservation, trips, payments etc... ?

**Comment by 305781** [comment]
done if j1-pull1 merged
