### ISSUE TITLE
Replace BaseReservationManager interface by standard class

### ISSUE THREAD

**Issue by NgyAnthony** [NgyAnthony/supinfo-2ccpp#4]
<img width="530" alt="Capture d’écran 2020-12-30 à 23 59 09" src="https://user-images.githubusercontent.com/26002874/103385498-040ade80-4afb-11eb-990c-328e5fed3e1f.png">

C++ doesn't allow virtual methods with templates, so I guess we have to ditch the interface and move the class specific objects to the children manager and implementing them as singleton with clear functions or create/destroy the objects every time we use new reservation objects. That sucks.

https://stackoverflow.com/questions/2919584/override-number-of-parameters-of-pure-virtual-functions

**Comment by 305781** [comment]
cleared if pull request accepted
